-- GENERATED by scripts/seed-gurgaon-places.ts — review before applying.
-- Source: docs/seed/gurgaon-venues.csv (the 10 `kitchens`-hub rows) · all 10
-- resolved via Places API 2026-07-03. Preserved as a standalone batch because
-- a follow-up full-CSV run hit the Places daily quota and overwrote the main
-- generated file; these values are copied verbatim from the successful run.
-- All 10 coords cluster within ~50m at Global Gateway Towers, MG Road,
-- Sector 26 (The Kitchens complex — Zomato/EazyDiner treat it as a locality).
-- Curated category/hub/zone are authoritative here (overwrite on conflict):
-- this is the founder seed, which find_or_create_place defers to.

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJUwg8OvEfDTkRcZ0XPmk1Y94', 'Anjeer - New Age Indian', 'Gurgaon', 28.4813367, 77.1039607, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJTwhpcgAfDTkR3DSG7HPBHUE', 'Easy Tiger by Boraan Thai', 'Gurgaon', 28.4813995, 77.1039689, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJA41ciHkfDTkRsk_NxMWqr9g', 'Vellam', 'Gurgaon', 28.4814806, 77.1039797, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJW2dZDwAfDTkRn4MNPJV-dNA', 'ASPER - Cocktail Bar', 'Gurgaon', 28.4811295, 77.1039434, 'cocktail_bar', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJv0Dl0jsfDTkR_buwYPZvtEs', 'Niko - Modern Asian', 'Gurgaon', 28.4815471, 77.1039934, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ56Yt5EYfDTkRfYv3ghBS31Y', 'The Fio Table - Gurugram', 'Gurgaon', 28.4815547, 77.1040055, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJk48dvSYfDTkRyVcJRD22lgI', 'Miss Margarita (Gurugram)', 'Gurgaon', 28.4813302, 77.1039538, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJP2dhg-8fDTkRIv7u20u9yUE', 'Mjöl Bake House', 'Gurgaon', 28.4810749, 77.104237, 'bakery_dessert', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJrYtlD7MfDTkRHUe5V9lJSsg', 'EVOO - Gurugram', 'Gurgaon', 28.4812869, 77.10395919999999, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJjZ5VkrsZDTkR0Y3IHIU8yAE', 'Fig at MG', 'Gurgaon', 28.4815244, 77.10427, 'cafe', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();
