-- GENERATED by scripts/seed-gurgaon-places.ts — review before applying.
-- Source: docs/seed/gurgaon-venues.csv · resolved 80/80 via Places API.
-- Curated category/hub/zone are authoritative here (overwrite on conflict):
-- this is the founder seed, which find_or_create_place defers to.

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJPdvhrs0ZDTkRJQws-tJOEKw', 'Comorin', 'Gurgaon', 28.4513368, 77.0966682, 'restaurant', 'gcr', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJbTc5i7UYDTkRSEKSd63it4U', 'Whisky Samba | Best Bar & Restaurant in Gurugram', 'Gurgaon', 28.4513881, 77.0968595, 'cocktail_bar', 'gcr', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJa5bce94YDTkRGM1q2A3zsUU', 'DiGhent Cafe', 'Gurgaon', 28.4683201, 77.0829914, 'cafe', 'crosspoint', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJF6QrXDgZDTkRXOymqHJU35o', 'Burma Burma Restaurant & Tea Room', 'Gurgaon', 28.494616299999997, 77.0885466, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJQWalWw8iDTkRK5nMn8laNhg', 'Farzi Cafe', 'Gurgaon', 28.495860699999998, 77.0887029, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJBd-UYzgZDTkRQSqUtLkFKC8', 'DLF CyberHub (Gurugram, Haryana)', 'Gurgaon', 28.4951598, 77.0892137, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJd0vqdjgZDTkR0JWGbToTpDs', 'The Wine Company', 'Gurgaon', 28.4958089, 77.0887259, 'bar', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJFTRVejgZDTkRAv_VZ27QdD8', 'Soi 7', 'Gurgaon', 28.4958599, 77.0886932, 'brewery', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJHeVicjgZDTkRjNIoUlH7SMY', 'Imperfecto Cyberhub', 'Gurgaon', 28.4959472, 77.08881629999999, 'live_music', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJpV08cjgZDTkRkkiaUcC-oOo', 'Dhaba Estd 1986 Delhi, Cyber Hub', 'Gurgaon', 28.4958831, 77.0886598, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJnbWpZTgZDTkROVaHpV-wLIU', 'MADE IN PUNJAB', 'Gurgaon', 28.4951749, 77.08839689999999, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJDwAAQDgZDTkRTqSf8HqD70w', 'Mamagoto Nomikai', 'Gurgaon', 28.4937814, 77.0883477, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ0yFk8TgZDTkRcumABA0rmQ4', 'Yum Yum Cha Cyberhub', 'Gurgaon', 28.494474999999998, 77.08753399999999, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJcZQiRTgZDTkR1NzcWoqONvc', 'Cyber Hub SOCIAL', 'Gurgaon', 28.4948543, 77.0889318, 'bar', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJRZJOT7wZDTkR-BCGXD-EI4E', 'Chai Garam Cafe, Cyber Hub', 'Gurgaon', 28.494081899999998, 77.0879756, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJbxPrejgZDTkRYVbL3QZyRSs', 'Punjab Grill DLF Cyber Hub', 'Gurgaon', 28.4959524, 77.088819, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJb320VjgZDTkRl7otOyF2Zvk', 'The Drunken Botanist', 'Gurgaon', 28.493889199999998, 77.0883356, 'cocktail_bar', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJM2rJOOMZDTkRzF0xheD9mYI', 'Ministry of Beer Gurgaon', 'Gurgaon', 28.468462000000002, 77.064418, 'brewery', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJVZUBq-cYDTkRwDKG7x1NNKs', 'prankster', 'Gurgaon', 28.4693819, 77.0633884, 'bar', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJieKNcTMZDTkR40zN0MBvc1o', 'Club Decode', 'Gurgaon', 28.468279, 77.0635037, 'brewery', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ-yw62ZgZDTkRU2-mfRo2OGc', 'Downtown Diner & Fresh Beer Cafe', 'Gurgaon', 28.468102599999998, 77.0629555, 'brewery', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJvcevPYojDTkRt365eOaMhBU', 'Molecule IFC - Best Rooftop Bar in Gurugram', 'Gurgaon', 28.4051872, 77.0583934, 'bar', 'm3m_ifc', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJQWDVVvwYDTkRSkhU6YscgKI', 'The Old School Brewhouse', 'Gurgaon', 28.4678027, 77.06416159999999, 'brewery', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJSWldVaoZDTkRDcBtrcYXkVo', 'The Groove', 'Gurgaon', 28.4613329, 77.04979430000002, 'bar', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJFyxgXssZDTkR13iln7wvV7U', 'The Potbelly – Gurgaon', 'Gurgaon', 28.461508100000003, 77.0498982, 'restaurant', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJPwbLZccjDTkR9_VeynCyZxc', 'Anardana M3M, IFC Gurugram', 'Gurgaon', 28.404885399999998, 77.058044, 'restaurant', 'm3m_ifc', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJbQ6SnVAjDTkRoZfLMrq3gQ4', 'Blue Tokai Coffee Roasters | AIPL Joy Street', 'Gurgaon', 28.3921292, 77.05934049999999, 'cafe', 'gc_ext', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJr5LfI4sZDTkRALDGI50ZtNg', 'Laidback Cafe - DLF CyberHub', 'Gurgaon', 28.495229799999997, 77.08848809999999, 'cafe', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJl2oNeN4YDTkRd-s7h2YI6R4', 'Sakley''s The Mountain Cafe', 'Gurgaon', 28.4675129, 77.08173239999999, 'cafe', 'galleria', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJGUu8JQAfDTkRTAL7uHxBiP0', 'The Kitchens', 'Gurgaon', 28.4815623, 77.103994, 'cafe', 'galleria', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJpdhppeEYDTkRnTQH7gfdljk', 'Downtown Galleria', 'Gurgaon', 28.4672514, 77.08117539999999, 'bar', 'galleria', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJSdDgY1AZDTkRkrWJJw3XwkA', 'Blue Tokai Coffee Roasters | DLF Cyber Park', 'Gurgaon', 28.502722, 77.090639, 'cafe', 'udyog_vihar', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJhTPI5y0ZDTkRsBjYOKp4TkI', 'Ikk Panjab', 'Gurgaon', 28.462989, 77.09649329999999, 'restaurant', 'udyog_vihar', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJFbB0ZLsjDTkRuiqGOWhSeD0', 'YouMee Airia Mall', 'Gurgaon', 28.382721600000004, 77.0524963, 'restaurant', 'sector_68_airia', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJg8Bhyv0YDTkRhp9dG7jYfBo', 'Open Tap 29', 'Gurgaon', 28.4682598, 77.06339109999999, 'bar', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJIQAAADAYDTkRp581qaKmibk', 'Quaff Brewing Co.', 'Gurgaon', 28.4941155, 77.0878888, 'club', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJVw3yP-gfDTkR26a0JQbdXzk', 'ToyBox Nightclub Gurgaon', 'Gurgaon', 28.469933899999997, 77.063019, 'cocktail_bar', 'gcr', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJpbagcDgZDTkRkE84awlcvEQ', 'Oh So Stoned! ...the icecream and shake joint', 'Gurgaon', 28.495808399999998, 77.08872819999999, 'bakery_dessert', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJtWZ73fQfDTkRT3-SstWdM08', 'Third Wave Coffee', 'Gurgaon', 28.433685699999998, 77.1051533, 'cafe', 'gcr', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJjwBNAdcjDTkRuct3gbLLz9E', 'Biryani Blues', 'Gurgaon', 28.409761, 77.10152099999999, 'restaurant', 'gcr', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJITMJgTMZDTkRa4Tzxu-kJCE', 'Mala-Akbari 32nd Avenue', 'Gurgaon', 28.4616962, 77.0497585, 'restaurant', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJE6ADl_QZDTkRpjivdc9mj08', 'Ophelia Clothes Shop', 'Gurgaon', 28.508931999999998, 77.031765, 'club', 'gcr', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJP65n3_0YDTkRk1qiInYdf1Y', 'Factory by Sutra', 'Gurgaon', 28.469095799999998, 77.062265, 'live_music', 'sector_29', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ9RFNhf4ZDTkR5asUH792G7o', 'YouMee DLF Cyber Hub', 'Gurgaon', 28.49526, 77.0882841, 'restaurant', 'cyberhub', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJUwg8OvEfDTkRcZ0XPmk1Y94', 'Anjeer - New Age Indian', 'Gurgaon', 28.4813367, 77.1039607, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJTwhpcgAfDTkR3DSG7HPBHUE', 'Easy Tiger by Boraan Thai', 'Gurgaon', 28.4813995, 77.1039689, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJA41ciHkfDTkRsk_NxMWqr9g', 'Vellam', 'Gurgaon', 28.4814806, 77.1039797, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJW2dZDwAfDTkRn4MNPJV-dNA', 'ASPER - Cocktail Bar', 'Gurgaon', 28.481129499999998, 77.10394339999999, 'cocktail_bar', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJv0Dl0jsfDTkR_buwYPZvtEs', 'Niko - Modern Asian', 'Gurgaon', 28.4815471, 77.1039934, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ56Yt5EYfDTkRfYv3ghBS31Y', 'The Fio Table - Gurugram', 'Gurgaon', 28.4815547, 77.1040055, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJk48dvSYfDTkRyVcJRD22lgI', 'Miss Margarita (Gurugram)', 'Gurgaon', 28.4813302, 77.1039538, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJP2dhg-8fDTkRIv7u20u9yUE', 'Mjöl Bake House', 'Gurgaon', 28.4810749, 77.104237, 'bakery_dessert', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJrYtlD7MfDTkRHUe5V9lJSsg', 'EVOO - Gurugram', 'Gurgaon', 28.4812869, 77.10395919999999, 'restaurant', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJjZ5VkrsZDTkR0Y3IHIU8yAE', 'Fig at MG', 'Gurgaon', 28.4815244, 77.10427, 'cafe', 'kitchens', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJM_anaxQZDTkR9VXoQw3rakU', 'The Piano Man Gurugram', 'Gurgaon', 28.4614516, 77.0498341, 'live_music', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJGZNNBuYZDTkRL5JX3k88-kE', 'Carnatic Cafe Gurugram', 'Gurgaon', 28.461707999999998, 77.0497791, 'cafe', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJyy954QYZDTkRIDWU4zGJ1yY', 'Fifth Avenue Cafe And Bakery', 'Gurgaon', 28.4617436, 77.0501931, 'bakery_dessert', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJZX-XJWcZDTkRg6ZKstyWzQM', 'Sandhouse - All Day Diner', 'Gurgaon', 28.4619769, 77.0502899, 'restaurant', '32nd_ave', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJw7dHGv4jDTkRUWT6kN8ahP4', 'Cafe Delhi Heights', 'Gurgaon', 28.406076, 77.0660071, 'restaurant', 'worldmark_65', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJXzECuj4jDTkRLo8g4VoICmU', 'Karim’s', 'Gurgaon', 28.3980294, 77.0720194, 'restaurant', 'worldmark_65', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJPw43a50jDTkRNTmypA_002Y', 'HOUZ Cafe Bar', 'Gurgaon', 28.3973776, 77.0722028, 'bar', 'worldmark_65', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJk0u5HlEjDTkR5TMwliPRGYA', 'The Beer Café', 'Gurgaon', 28.3976814, 77.0719809, 'brewery', 'worldmark_65', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJUUg5DYkjDTkR3jsfQ78wsYM', 'Thalaivar', 'Gurgaon', 28.398053599999997, 77.0721203, 'restaurant', 'worldmark_65', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ3YlCAdEjDTkRtYhrNafuBUs', 'Wanchai by kylin', 'Gurgaon', 28.398037100000003, 77.0720228, 'restaurant', 'worldmark_65', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ7wkuLiIZDTkRzogQTRwgduY', 'AB''s - Absolute Barbecues | MGF Mall, Gurugram', 'Gurgaon', 28.4791898, 77.0823704, 'restaurant', 'mg_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJG6XSXvohDTkRXILI0z_EvOw', 'Pirates of Grill', 'Gurgaon', 28.479736199999998, 77.08964929999999, 'restaurant', 'mg_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJPa7lA9QeDTkRh-eFe-2V66M', 'Longitude Bar', 'Gurgaon', 28.480572, 77.107944, 'cocktail_bar', 'mg_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ38bPB0wZDTkR6yM-Q2IXgPk', 'Zambar', 'Gurgaon', 28.5029693, 77.0972073, 'restaurant', 'mg_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJIRyQ86wjDTkRKm1z2sktnfM', 'Citrus Café by Lemon Tree', 'Gurgaon', 28.370251, 77.057267, 'cafe', 'sohna_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJnQMz2MEjDTkRq0LhBgbi-uU', 'The Brewhouse', 'Gurgaon', 28.4166603, 77.0415115, 'brewery', 'sohna_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJBe68_pEiDTkRmVVhUYPTlKA', 'THE NOOK ( Tuckinn Fresh Beer cafe )', 'Gurgaon', 28.40634, 77.0446327, 'restaurant', 'sohna_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJea1rBJIiDTkRhdO9EyIlCsI', 'Vatika Business Centre & Co-working Spaces', 'Gurgaon', 28.405845499999998, 77.04448839999999, 'street_food', 'sohna_road', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJ35alpksZDTkRB8bxjxA1vx4', 'Yeti - The Himalayan Kitchen, Cross Point', 'Gurgaon', 28.468211999999998, 77.08353, 'restaurant', 'crosspoint', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJr-aFlN4YDTkRaWom3eqx2ak', 'Getafix Cafe', 'Gurgaon', 28.468295299999998, 77.0833389, 'cafe', 'crosspoint', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJC5o_kt4YDTkR6YIZGNYqUPQ', 'The Pasta Bowl Company', 'Gurgaon', 28.4682763, 77.0830587, 'restaurant', 'crosspoint', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJFUyKJ9oYDTkRN-0BswiHUqc', 'Cross Point Mall', 'Gurgaon', 28.4683633, 77.08290579999999, 'restaurant', 'crosspoint', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJv86r-9oZDTkR7hUDGRk66tI', 'Downtown South Point mall', 'Gurgaon', 28.448342999999998, 77.09947000000001, 'restaurant', 'south_point', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJa8HaUbQYDTkRe-p_pvrW5sk', 'Cafe Amaretto', 'Gurgaon', 28.4481808, 77.09902129999999, 'cafe', 'south_point', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJAQAAUbQYDTkRpVKOx8FlMHQ', 'Midam Korean Barbecue Restaurant', 'Gurgaon', 28.4482242, 77.0990061, 'restaurant', 'south_point', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();

insert into public.canonical_places (google_place_id, name, destination_text, lat, lng, category, hub, zone)
values ('ChIJjffYJ4gZDTkRILJOrR3ZGi0', 'Vagator Beach Shack', 'Gurgaon', 28.4476327, 77.0994695, 'restaurant', 'south_point', 'gurgaon')
on conflict (google_place_id) do update set
  name = excluded.name, lat = excluded.lat, lng = excluded.lng,
  category = excluded.category, hub = excluded.hub, zone = excluded.zone,
  updated_at = now();
